# Generated by Django 4.2.4 on 2023-08-16 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencyapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='currency',
        ),
        migrations.AddField(
            model_name='country',
            name='currencies',
            field=models.CharField(default='$', max_length=100),
            preserve_default=False,
        ),
    ]
